name: Run specs on supported Solidus versions

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.database }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.3"
        database:
          - "postgresql"
          - "mysql"
        # ruby-version: ["3.1", "3.2", "3.3"]
        # database: ["postgresql", "mysql", "sqlite"]
        # rails-version: ["7.0", "7.1"]
        # solidus-branch: ["v4.3", "v4.4"]
    steps:
      - uses: actions/checkout@v4
      - name: Run extension tests
        uses: solidusio/test-solidus-extension@main
        with:
          database: ${{ matrix.database }}
          ruby-version: ${{ matrix.ruby-version }}